/**
 *  ++=================++
 *  ||  StandCalendar  ||
 *  ++=================++
 *  ++===========================++
 *  ||  JS Module  |  polyfills  ||
 *  ++===========================++
 *
 *  polyfills/.
 *  index.js
 *
 *  js script for added polyfills to support IE/EDGE/FIREFOX/SAFARI
 *  base script imports babel-polyfill, which will do most of the work
 *  https://babeljs.io/docs/en/babel-polyfill/
 *
 *  +-------------------------------+
 *  |  generated by Cameron Vargas  |
 *  +-------------------------------+
 *
 **/

import 'babel-polyfill'
