/**
 *  ++=================++
 *  ||  StandCalendar  ||
 *  ++=================++
 *  ++==========================++
 *  ||  JS Module  |  calendar  ||
 *  ++==========================++
 *
 *  calendar/.
 *  actions/.
 *  types.js
 *
 *  contains all actions types for redux action creators and reducers for the app
 *  https://redux.js.org/basics/actions
 *
 *  +-------------------------------+
 *  |  generated by Cameron Vargas  |
 *  +-------------------------------+
 *
 **/

/**
 *
 *  EXAMPLE ACTION TYPES:
 *  ========================
 *
 *  export const SET_USER = 'set_authorized_username';
 *  export const REMOVE_USER = 'remove_authorized_username'
 *
 **/

export const UPDATE_COUNTER = 'update_click_counter'
export const RESET_COUNTER = 'reset_click_counter'
