/**
 *  ++=================++
 *  ||  StandCalendar  ||
 *  ++=================++
 *  ++==========================++
 *  ||  JS Module  |  calendar  ||
 *  ++==========================++
 *
 *  calendar/.
 *  containers/.
 *  App.js
 *
 *  Sample Container. Renders both ReactSpinner and ClickCounter, sets up redux
 *  hook and passes down updated data to each of the components as needed
 *
 *  +-------------------------------+
 *  |  generated by Cameron Vargas  |
 *  +-------------------------------+
 *
 **/

import React, { Component } from 'react'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import PropTypes from 'prop-types'

import * as actions from '../actions'

import DnDCalendar from '../components/DnDCalendar'

export class App extends Component {
  constructor (props) {
    super(props)
    this.handleReactClick = this.handleReactClick.bind(this)
    this.handleCounterClick = this.handleCounterClick.bind(this)
  }

  UNSAFE_componentWillMount () {
  }

  UNSAFE_componentWillReceiveProps (nextProps) {
  }

  handleReactClick () {
    const current_click_num = this.props.clicks
    this.props.actions.updateCounter(current_click_num + 1)
  }
  handleCounterClick () {
    this.props.actions.resetCounter()
  }

  render () {
    return (
      <div className='app-container'>
        <DnDCalendar />
      </div>
    )
  }
}

App.propTypes = {
  clicks: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.number
  ]),
  actions: PropTypes.object
}

function mapDispatchToProps (dispatch) {
  return {
    actions: bindActionCreators(actions, dispatch)
  }
}

export default connect(state => {
  const clicks = state.clicks

  return {
    clicks
  }
}, mapDispatchToProps)(App)
